### ISSUE TITLE
Python version & PyPI release

### ISSUE THREAD

**Issue by Yomguithereal** [dw/csvmonkey#2]
Hello @dw. I don't find it mentioned here but I guess your library works with python 2, no?

Also, would you be open to a release on the [PyPI](https://pypi.org/) registry so anyone can easily install the library using `pip install csvmonkey`? Sorry if you have already released and I could not find your package.

**Comment by dw** [comment]
It's not on pyi yet -- i think tbe packaging may need a little work first.
Will take a look this weekend :)

You can of course just "pip install git+https://github.com/dw/csvmonkey.git"
in the meantime

**Comment by dw** [comment]
Finally there is a release on PyPI.

**Comment by dw** [comment]
please open a bug for it so I don't forget :) Porting C extensions is usually much simpler than Python code (believe it or not)
