### ISSUE TITLE
pre-compiled package

### ISSUE THREAD

**Issue by h5rdly** [dw/csvmonkey#5]
Hi,

First of all, cheers for this awesome project.

I was wondering whether it would be possible to add some precompiled binaries ("bdist") to the wheel. 
This allows adding csvmonkey as a dependency, without worrying about the user getting compile errors when pip installing. 

In my case at work, I got some gcc error (I think gcc version 4.8 may be too old) and didn't manage to perform any tests.

I believe numpy, cython etc. moved to that MO, which makes installing them a breeze whether you're on linux or other platform.

Thanks,
Eli

**Comment by dw** [comment]
I'm not working on this right now. Closing the ticket and making the repo PR only. Apologies for the inconvenience -- feel free to send patches. :)  Thanks
