### ISSUE TITLE
cpython/csvmonkey.cpp:933:1: sorry, unimplemented: non-trivial designated initializers not supported

### ISSUE THREAD

**Issue by jdonnerstag** [dw/csvmonkey#6]
Hi, 

this error occurs on my WSL (windows Ubuntu Linux) with the following compiler: 
<pre>...:~/csvmonkey$ gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.</pre>

When using Clang it builds successfully.
<pre>...:~/csvmonkey$ clang --version
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin</pre>

The full errror message is:
<pre>...:~/csvmonkey$ python3 setup.py build --force
running build
running build_ext
building 'csvmonkey' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -UNDEBUG -I/usr/include/python3.6m -c cpython/csvmonkey.cpp -o build/temp.linux-x86_64-3.6/cpython/csvmonkey.o -std=c++11 -Iinclude -O3 -w -Wno-strict-prototypes -msse4.2
cc1plus: warning: command line option ‘-Wno-strict-prototypes’ is valid for C/ObjC but not for C++
cpython/csvmonkey.cpp:933:1: sorry, unimplemented: non-trivial designated initializers not supported
 };
 ^
cpython/csvmonkey.cpp:933:1: sorry, unimplemented: non-trivial designated initializers not supported
cpython/csvmonkey.cpp:933:1: sorry, unimplemented: non-trivial designated initializers not supported
cpython/csvmonkey.cpp:933:1: sorry, unimplemented: non-trivial designated initializers not supported
cpython/csvmonkey.cpp:933:1: sorry, unimplemented: non-trivial designated initializers not supported
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1</pre>

According to the [example](https://docs.python.org/3/c-api/typeobj.html#typedef-examples) it looking all good, including the order of the variables.  Any idea what could cause the issue?

**Comment by jdonnerstag** [comment]
With clang I also had to add
<pre>extra_link_args += ['-lstdc++']</pre>
to setup.py to prevent 
<pre>undefined symbol: _ZTVN10__cxxabiv117__class_type_infoE</pre> error when loading the module.

**Comment by dmnobunaga** [comment]
Is there any way to fix g++ compilation?

**Comment by dw** [comment]
I'm not working on this right now. Closing the ticket and making the repo PR only. Apologies for the inconvenience -- feel free to send patches. :)  Thanks
