### ISSUE TITLE
Not able to download anon-ram.csv.zstd

### ISSUE THREAD

**Issue by jdonnerstag** [dw/csvmonkey#7]
There seem to be some (volume) restrictions on your LFS account preventing me from downloading the file.

**Comment by jdonnerstag** [comment]
Git LFS: (0 of 1 files) 0 B / 2.02 MB
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/dw/csvmonkey.git/info/lfs'

**Comment by dw** [comment]
I'm not working on this right now. Closing the ticket and making the repo PR only. Apologies for the inconvenience -- feel free to send patches. :)  Thanks
